server:
  port: 8080
  servlet:
    session:
      timeout: 30m   #session 会话超时时间  默认30分钟  至少1分钟
      cookie:
        name: JSESSIONID #指定浏览器cookie中关于SessionID 保存的那个名称 方便删除时统一处理
spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: 654123
    url: jdbc:mysql://127.0.0.1:3306/study-security?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  session:
    store-type: redis #session存储方式redis
#  redis:
#    port: 6379

mybatis-plus:
  # 指定实体类所有包
  type-aliases-package: springsecurity.entities

# 日志级别，会打印sql语句
logging:
  level:
    com.mengxuegu.web.mapper: debug

myproject:
  security:
    authentication:
      loginPage: /login/page # 响应认证页面的URL
      loginProcessingUrl: /login/form # 指定登录请求url
      usernameParameter: name #参数用户名 默认 username
      passwordParameter: pwd #密码       默认 password
      staticPaths: #静态资源 "/dist/**", "modules/**", "/plugins/**"
        - /dist/**
        - /modules/**
        - /plugins/**
      logintype: REDIRECT
      #  "/code/image","/mobile/page","/code/mobile"
      imageCodeUrl: /code/image  #获取图形验证码地址
      mobileCodeUrl: /code/mobile #获取手机验证码请求
      mobilePage: /mobile/page #前往手机登录页面
      tokenValiditySeconds: 3600 #记住我功能有效时长 秒
